### PR TITLE
Update closeAll function to ensure instance.close() can be executed with...

### PR DESCRIPTION
**Pull request by albertshaw**
...out JS error

The prototype of Array may be changed by others, so at least we have to make sure the instance.close is a Function.

### CODE REVIEW

**Comment by albertshaw** [comment]
```
EasyDropDown.prototype = {
                constructor: EasyDropDown,
                instances: [],
...
```

The instances is initialed as an Array, so even thought Object keyed by the instance's ID, the instances is still treated as Array when you trying to loop it.

```
var instantiate = function(domNode, settings){
                        domNode.id = !domNode.id ? 'EasyDropDown'+rand() : domNode.id;
                        var instance = new EasyDropDown();
                        if(!instance.instances[domNode.id]){
                                instance.instances[domNode.id] = instance;
...
```

And in my project, we add an function to the prototype of array like below:

```
Array.prototype.insertAt = function(){
    blah blah...
}
```

Thus will lead a 'For...In...' loop issue to Array.
Simply initial the instances as {} would also fix it.

**Comment by patrickkunka** [comment]
Thanks for the info - I will work it into the next version.

**Comment by albertshaw** [comment]
Thank you
Your easydropdown is really AWESOME, and helps me a lot.

**Comment by zzolo** [comment]
+1  I have run into similar issues.

**Pull request closed without merging**
